name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: "cache-spm"
        with:
          path: BuildTools/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/BuildTools/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build tools
        if: steps.cache-spm.outputs.cache-hit != 'true'
        run: swift run -c release --package-path BuildTools swift-format lint -p --strict --recursive ./Sources ./Tests ./scripts
      - name: Lint
        run: |
          swift run -c release --skip-build --package-path BuildTools swift-format --version
          swift run -c release --skip-build --package-path BuildTools swift-format lint -p --strict --recursive ./Sources ./Tests ./scripts
      - name: Build
        run: swift build

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          swift test --enable-code-coverage
          xcrun llvm-cov export -format="lcov" .build/debug/TwitterAPIKitPackageTests.xctest/Contents/MacOS/TwitterAPIKitPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" > info.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
